version: "3.3"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:80"
    networks:
      - global
  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: front
    ports:
      - "5001:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    volumes:
      - ".:/app"
      - "/app/node_modules"
    networks:
      - global

networks:
  global:
