version: "3.3"

services:
  backend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=5000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1234
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - 8001:80
      - 5000:443
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    networks:
      - global
    volumes:
      - ~/.aspnet/https:/https:ro
  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: front
    ports:
      - "5002:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    volumes:
      - ".:/app"
      - "/app/node_modules"
    networks:
      - global

networks:
  global:
