version: "3.3"

services:
  db:
    image: postgres:latest
    container_name: postgresdbBattleShip
    restart: always
    environment:
      HOST: "localhost"
      POSTGRES_USER: "UserPawel"
      POSTGRES_PASSWORD: "Password1234"
      POSTGRES_DB: "postgresdbBattleShip"
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - global
  backend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=5000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1234
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - 8001:80
      - 5000:443
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    networks:
      - global
    volumes:
      - ./certificates/https:/https:ro
    depends_on:
      - db
  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: front
    ports:
      - "5002:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    volumes:
      - ".:/app"
      - "/app/node_modules"
    networks:
      - global
volumes:
  db:
    driver: local

networks:
  global:
